# Hungarian translation of pybliographer.
# Copyright (C) 2004, 2005 Free Software Foundation, Inc.
# This file is distributed under the same license as the pybliographer package.
#
# Zoltán Kóta <kota at gnome dot hu>, 2004-2010.
# Balázs Úr <urbalazs at gmail dot com>, 2014.
msgid ""
msgstr ""
"Project-Id-Version: pybliographer\n"
"Report-Msgid-Bugs-To: http://bugzilla.gnome.org/enter_bug.cgi?"
"product=pybliographer&keywords=I18N+L10N&component=general\n"
"POT-Creation-Date: 2014-05-17 18:42+0000\n"
"PO-Revision-Date: 2014-09-21 00:58+0200\n"
"Last-Translator: Balázs Úr <urbalazs@gmail.com>\n"
"Language-Team: Hungarian <gnome@gnome.hu>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Lokalize 1.2\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../Pyblio/Autoload.py:78
#, python-format
msgid "warning: can't import %s: %s"
msgstr "figyelmeztetés: %s nem importálható: %s"

#: ../Pyblio/Config.py:52
#, python-format
msgid "value of `%s' should be of type %s"
msgstr "a(z) „%s” értékének %s típusúnak kell lennie"

#: ../Pyblio/Config.py:212
msgid "String"
msgstr "Karakterlánc"

#: ../Pyblio/Config.py:221
msgid "Boolean"
msgstr "Logikai"

#: ../Pyblio/Config.py:240
msgid "Integer"
msgstr "Egész"

#: ../Pyblio/Config.py:242
#, python-format
msgid "Integer under %d"
msgstr "Egész %d alatt"

#: ../Pyblio/Config.py:244
#, python-format
msgid "Integer over %d"
msgstr "Egész %d felett"

#: ../Pyblio/Config.py:246
#, python-format
msgid "Integer between %d and %d"
msgstr "Egész %d és %d között"

#: ../Pyblio/Config.py:258
#, python-format
msgid "Element in `%s'"
msgstr "Elem ebben: „%s”"

#: ../Pyblio/Config.py:278
#, python-format
msgid "Tuple (%s)"
msgstr "Szekvencia (%s)"

#: ../Pyblio/Config.py:299
#, python-format
msgid "List (%s)"
msgstr "Lista (%s)"

#: ../Pyblio/Config.py:324
#, python-format
msgid "Dictionary (%s, %s)"
msgstr "Szótár (%s, %s)"

#: ../Pyblio/Config.py:344
#, python-format
msgid "warning: could not restore setting %r to %r: %s"
msgstr ""
"figyelmeztetés: a(z) %r - %r beállítás-változtatást nem lehet végrehajtani: "
"%s"

#: ../Pyblio/Fields.py:261
msgid "Illegal year value"
msgstr "Érvénytelen év érték"

#: ../Pyblio/Fields.py:265
msgid "Illegal month value"
msgstr "Érvénytelen hónap érték"

#: ../Pyblio/Fields.py:269
msgid "Illegal day value"
msgstr "Érvénytelen nap érték"

#: ../Pyblio/Fields.py:510
#, python-format
msgid "in %s"
msgstr "ebben: %s"

#: ../Pyblio/Format/BibTeX.py:323 ../Pyblio/Format/BibTeX.py:371
#, python-format
msgid "key `%s' is malformed"
msgstr "a(z) „%s” kulcs helytelen"

#: ../Pyblio/Format/BibTeX.py:340 ../Pyblio/Format/BibTeX.py:359
#, python-format
msgid "%s:%d: key `%s' already defined"
msgstr "%s:%d: a(z) „%s” kulcs már definiálva van"

#: ../Pyblio/GnomeUI/Config.py:147 ../Pyblio/GnomeUI/Fields.py:417
msgid ""
"Some changes require to restart Pybliographic\n"
"to be correctly taken into account"
msgstr ""
"Néhány változás megfelelő figyelembevételéhez\n"
"a Pybliographic újraindítása szükséges"

#: ../Pyblio/GnomeUI/Config.py:429
msgid "Add"
msgstr "Hozzáadás"

#: ../Pyblio/GnomeUI/Config.py:432
msgid "Update"
msgstr "Frissítés"

#: ../Pyblio/GnomeUI/Config.py:435 ../Pyblio/GnomeUI/Config.py:549
msgid "Remove"
msgstr "Eltávolítás"

#: ../Pyblio/GnomeUI/Config.py:546
msgid "Set"
msgstr "Beállítás"

#: ../Pyblio/GnomeUI/Config.py:561
msgid "Key:"
msgstr "Kulcs:"

#: ../Pyblio/GnomeUI/Config.py:563
msgid "Value:"
msgstr "Érték:"

#. id     stock            label         accel   tooltip   callback
#: ../Pyblio/GnomeUI/Document.py:145
msgid "_File"
msgstr "_Fájl"

#: ../Pyblio/GnomeUI/Document.py:146
msgid "_Edit"
msgstr "S_zerkesztés"

#: ../Pyblio/GnomeUI/Document.py:147
msgid "_View"
msgstr "_Nézet"

#: ../Pyblio/GnomeUI/Document.py:148
msgid "_Cite"
msgstr "_Idézés"

#: ../Pyblio/GnomeUI/Document.py:149
msgid "_Settings"
msgstr "_Beállítások"

#: ../Pyblio/GnomeUI/Document.py:150
msgid "_Help"
msgstr "_Súgó"

#: ../Pyblio/GnomeUI/Document.py:151
msgid "Recent documents"
msgstr "Előző dokumentumok"

#: ../Pyblio/GnomeUI/Document.py:154
msgid "Open a file"
msgstr "Fájl megnyitása"

#: ../Pyblio/GnomeUI/Document.py:155
msgid "Open _Location"
msgstr "_Hely megnyitása"

#: ../Pyblio/GnomeUI/Document.py:156
msgid "Save the current file"
msgstr "Aktuális fájl mentése"

#: ../Pyblio/GnomeUI/Document.py:161
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:3
msgid "Merge With..."
msgstr "Hozzáfűzés…"

#: ../Pyblio/GnomeUI/Document.py:162
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:4
msgid "Medline Query..."
msgstr "Medline keresés…"

#: ../Pyblio/GnomeUI/Document.py:170
msgid "Add a new entry"
msgstr "Új bejegyzés hozzáadása"

#: ../Pyblio/GnomeUI/Document.py:175
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:9
msgid "S_ort..."
msgstr "_Rendezés…"

#: ../Pyblio/GnomeUI/Document.py:176
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:11
msgid "Cite..."
msgstr "Idézés…"

#: ../Pyblio/GnomeUI/Document.py:176
msgid "Cite key(s)"
msgstr "Kulcs(ok) idézése"

#: ../Pyblio/GnomeUI/Document.py:177
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:12
msgid "Format..."
msgstr "Formázás…"

#: ../Pyblio/GnomeUI/Document.py:179
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:14
msgid "Fields..."
msgstr "Mezők…"

#: ../Pyblio/GnomeUI/Document.py:181
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:15
msgid "Forget all changes"
msgstr "Felejtsen el minden változást"

#: ../Pyblio/GnomeUI/Document.py:185
msgid "_Resource"
msgstr "_Erőforrás"

#: ../Pyblio/GnomeUI/Document.py:236
msgid "Quick search"
msgstr "Gyorskeresés"

#: ../Pyblio/GnomeUI/Document.py:310
msgid "Unnamed bibliographic database"
msgstr "Névtelen bibliográfiai adatbázis"

#: ../Pyblio/GnomeUI/Document.py:393
#, python-format
msgid ""
"can't open file `%s' for writing:\n"
"%s"
msgstr ""
"nem lehet írásra megnyitni a(z) „%s” fájlt:\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:414
#, python-format
msgid ""
"Error while parsing `%s':\n"
"%s"
msgstr ""
"Hiba a(z) „%s” feldolgozása során:\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:430
msgid "New database"
msgstr "Új adatbázis"

#: ../Pyblio/GnomeUI/Document.py:438 ../Pyblio/GnomeUI/Document.py:442
msgid "[no entry]"
msgstr "[nincs bejegyzés]"

#: ../Pyblio/GnomeUI/Document.py:439
msgid "[1 entry]"
msgstr "[1 bejegyzés]"

#: ../Pyblio/GnomeUI/Document.py:440
#, python-format
msgid "[%d entries]"
msgstr "[%d bejegyzés]"

#: ../Pyblio/GnomeUI/Document.py:443
#, python-format
msgid "[%d/1 entry]"
msgstr "[%d/1 bejegyzés]"

#: ../Pyblio/GnomeUI/Document.py:444
#, python-format
msgid "[%d/%d entries]"
msgstr "[%d/%d bejegyzés]"

#: ../Pyblio/GnomeUI/Document.py:449
msgid "[modified]"
msgstr "[módosítva]"

#: ../Pyblio/GnomeUI/Document.py:452
#, python-format
msgid "view limited to: %s"
msgstr "megjelenítési limit: %s"

#: ../Pyblio/GnomeUI/Document.py:465
msgid ""
"The database has been modified.\n"
"Discard changes?"
msgstr ""
"Az adatbázis módosítva lett.\n"
"Eldobja a változásokat?"

#: ../Pyblio/GnomeUI/Document.py:469
msgid ""
"The database has been modified.\n"
"Save changes?"
msgstr ""
"Az adatbázis módosítva lett.\n"
"Elmenti a változásokat?"

#: ../Pyblio/GnomeUI/Document.py:490
#| msgid ""
#| "The database has been externally modified.\n"
#| "Overwrite changes ?"
msgid ""
"The database has been externally modified.\n"
"Overwrite changes?"
msgstr ""
"Az adatbázis külsőleg módosítva lett.\n"
"Felülírja a változásokat?"

#. no result.
#: ../Pyblio/GnomeUI/Document.py:519
msgid "Your query returned no result"
msgstr "A keresés eredménytelen volt"

#. error
#: ../Pyblio/GnomeUI/Document.py:523
msgid "An error occured during Medline Query"
msgstr "Hiba történt a medline keresés során"

#. get a new file name
#: ../Pyblio/GnomeUI/Document.py:533
msgid "Merge file"
msgstr "Fájl hozzáfűzése"

#: ../Pyblio/GnomeUI/Document.py:546 ../Pyblio/GnomeUI/Document.py:633
msgid "Open error"
msgstr "Megnyitási hiba"

#: ../Pyblio/GnomeUI/Document.py:570
msgid "Merge status"
msgstr "Hozzáfűzés állapota"

#. get a new file name
#: ../Pyblio/GnomeUI/Document.py:581
msgid "Open file"
msgstr "Fájl megnyitása"

#: ../Pyblio/GnomeUI/Document.py:619
msgid ""
"An autosave file was found which is newer than the original file.\n"
"Do you want to restore it?"
msgstr ""
"A megnyitandó fájlnál egy újabb, automatikusan elmentett biztonsági fájlt "
"találtam.\n"
"Kívánja visszaállítani?"

#: ../Pyblio/GnomeUI/Document.py:654 ../Pyblio/GnomeUI/Document.py:795
#: ../Pyblio/GnomeUI/Document.py:855
#, python-format
msgid ""
"Unable to remove autosave file `%s':\n"
"%s"
msgstr ""
"Nem lehet a(z) `%s' fájlt eltávolítani:\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:705
#, python-format
msgid ""
"Error during autosaving:\n"
"%s"
msgstr ""
"Hiba az automatikus mentés során:\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:733
#, python-format
msgid ""
"Unable to save `%s':\n"
"%s"
msgstr ""
"Nem lehet `%s'-t menteni:\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:741
msgid ""
"An internal error occured during saving\n"
"Try to Save As..."
msgstr ""
"Belső hiba történt a mentés során\n"
"Próbálja más néven: Mentés másként..."

#: ../Pyblio/GnomeUI/Document.py:756
msgid "Save As..."
msgstr "Mentés másként..."

#: ../Pyblio/GnomeUI/Document.py:762
#, python-format
#| msgid ""
#| "The file `%s' already exists.\n"
#| "Overwrite it ?"
msgid ""
"The file `%s' already exists.\n"
"Overwrite it?"
msgstr ""
"A(z) „%s” fájl már létezik.\n"
"Felülírja?"

#: ../Pyblio/GnomeUI/Document.py:769
#, python-format
msgid ""
"During opening:\n"
"%s"
msgstr ""
"A megnyitás során:\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:807
msgid "Reopen error"
msgstr "Megnyitási hiba"

#: ../Pyblio/GnomeUI/Document.py:880
#, python-format
#| msgid ""
#| "An entry called `%s' already exists.\n"
#| "Rename and add it anyway ?"
msgid ""
"An entry called `%s' already exists.\n"
"Rename and add it anyway?"
msgstr ""
"Már létezik „%s” néven bejegyzés.\n"
"Akarja, hogy átnevezzük és hozzáadjuk?"

#: ../Pyblio/GnomeUI/Document.py:917
#| msgid "Really remove all the entries ?"
msgid "Really remove all the entries?"
msgstr "Valóban törölni akarja az összes bejegyzést?"

#: ../Pyblio/GnomeUI/Document.py:937
msgid "Create new entry"
msgstr "Új bejegyzés"

#: ../Pyblio/GnomeUI/Document.py:951
#, python-format
#| msgid "Really edit %d entries ?"
msgid "Really edit %d entries?"
msgstr "Valóban szerkeszteni akar %d bejegyzést?"

#: ../Pyblio/GnomeUI/Document.py:998
#, python-format
#| msgid "Remove all the %d entries ?"
msgid "Remove all the %d entries?"
msgstr "Eltávolítja mind a(z) %d bejegyzést?"

#: ../Pyblio/GnomeUI/Document.py:1000
#, python-format
#| msgid "Remove entry `%s' ?"
msgid "Remove entry `%s'?"
msgstr "Eltávolítja a(z) „%s” bejegyzést?"

#: ../Pyblio/GnomeUI/Document.py:1019
msgid ""
"your search text must contain\n"
"latin-1 characters only"
msgstr ""
"A keresési kulcsszavak csak latin-1\n"
"karaktereket tartalmazhatnak"

#: ../Pyblio/GnomeUI/Document.py:1098 ../Pyblio/GnomeUI/Document.py:1106
#, python-format
msgid ""
"Can't connect to LyX:\n"
"%s"
msgstr ""
"Nem lehet kapcsolódni a LyX-hez:\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:1222
#, python-format
msgid ""
"Can't display documentation:\n"
"%s"
msgstr ""
"Nem lehet megjeleníteni a dokumentációt:\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:1230
msgid "This program is copyrighted under the GNU GPL"
msgstr "Ez a program a GNU GPL-nek megfelelő szerzői joggal védett"

#: ../Pyblio/GnomeUI/Document.py:1231
msgid "GNOME interface to the Pybliographer system."
msgstr "GNOME felület a Pybliographer rendszerhez."

#: ../Pyblio/GnomeUI/Document.py:1242
msgid "GNOME Translation Team"
msgstr "GNOME fordítócsapat"

#: ../Pyblio/GnomeUI/Document.py:1247
msgid "Pybliographer Home Page"
msgstr "Pybliographer honlapja"

#: ../Pyblio/GnomeUI/Editor.py:35
msgid "Last Name, First Name"
msgstr "Vezetéknév, Keresztnév"

#: ../Pyblio/GnomeUI/Editor.py:36 ../Pyblio/GnomeUI/Editor.py:1292
#: ../Pyblio/GnomeUI/Fields.py:39 ../Pyblio/GnomeUI/glade/config1.glade.h:10
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:9
msgid "Text"
msgstr "Szöveg"

#: ../Pyblio/GnomeUI/Editor.py:133 ../Pyblio/GnomeUI/Editor.py:1003
msgid "Error in native string parsing"
msgstr "Hiba a karakterlánc elemzésében"

#: ../Pyblio/GnomeUI/Editor.py:312
msgid "Day"
msgstr "Nap"

#: ../Pyblio/GnomeUI/Editor.py:321
msgid "Month"
msgstr "Hónap"

#: ../Pyblio/GnomeUI/Editor.py:330
msgid "Year"
msgstr "Év"

#: ../Pyblio/GnomeUI/Editor.py:355
msgid "Invalid day field in date"
msgstr "Érvénytelen nap a dátumban"

#: ../Pyblio/GnomeUI/Editor.py:363
msgid "Invalid month field in date"
msgstr "Érvénytelen hónap a dátumban"

#: ../Pyblio/GnomeUI/Editor.py:371
msgid "Invalid year field in date"
msgstr "Érvénytelen év a dátumban"

#. A delete button
#: ../Pyblio/GnomeUI/Editor.py:419 ../Pyblio/GnomeUI/Search.py:86
msgid "Delete"
msgstr "Törlés"

#: ../Pyblio/GnomeUI/Editor.py:430 ../Pyblio/GnomeUI/Editor.py:443
#: ../Pyblio/GnomeUI/Editor.py:446
msgid "[ Drop an Entry here ]"
msgstr "[ Dobjon ide egy bejegyzést ]"

#: ../Pyblio/GnomeUI/Editor.py:502
msgid "Browse..."
msgstr "Tallózás…"

#: ../Pyblio/GnomeUI/Editor.py:525
msgid "Select file"
msgstr "Fájl kiválasztása"

#: ../Pyblio/GnomeUI/Editor.py:549 ../Pyblio/GnomeUI/Fields.py:236
#: ../Pyblio/GnomeUI/glade/config1.glade.h:12
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:11
msgid "Entry type"
msgstr "Bejegyzés típusa"

#: ../Pyblio/GnomeUI/Editor.py:551
msgid "Key"
msgstr "Kulcs"

#: ../Pyblio/GnomeUI/Editor.py:600
msgid "Create Field"
msgstr "Mező létrehozása"

#. navigation buttons
#: ../Pyblio/GnomeUI/Editor.py:605
msgid "Back"
msgstr "Vissza"

#: ../Pyblio/GnomeUI/Editor.py:608
msgid "Next"
msgstr "Következő"

#: ../Pyblio/GnomeUI/Editor.py:728 ../Pyblio/GnomeUI/Fields.py:451
msgid "Mandatory"
msgstr "Kötelező"

#: ../Pyblio/GnomeUI/Editor.py:728 ../Pyblio/GnomeUI/Fields.py:452
msgid "Optional"
msgstr "Opcionális"

#: ../Pyblio/GnomeUI/Editor.py:728 ../Pyblio/GnomeUI/Editor.py:1207
msgid "Notes"
msgstr "Jegyzetek"

#: ../Pyblio/GnomeUI/Editor.py:728
msgid "Extra"
msgstr "Extra"

#: ../Pyblio/GnomeUI/Editor.py:909
msgid "Invalid key format"
msgstr "Érvénytelen kulcsformátum"

#: ../Pyblio/GnomeUI/Editor.py:917
#, python-format
msgid "Key `%s' already exists"
msgstr "A(z) „%s” kulcs már létezik"

#: ../Pyblio/GnomeUI/Editor.py:934
#, python-format
msgid "The `%s' field contains a non Latin-1 symbol"
msgstr "A(z) „%s” mező nem Latin-1 szimbólumot tartalmaz"

#: ../Pyblio/GnomeUI/Editor.py:996
msgid "Your text contains non Latin-1 symbols"
msgstr "A szöveg nem Latin-1 szimbólumokat tartalmaz"

#: ../Pyblio/GnomeUI/Editor.py:1023
msgid "Edit entry"
msgstr "Bejegyzés szerkesztése"

#: ../Pyblio/GnomeUI/Editor.py:1037 ../Pyblio/GnomeUI/Editor.py:1102
msgid "Native Editing"
msgstr "Natív szerkesztés"

#: ../Pyblio/GnomeUI/Editor.py:1125
msgid "Standard Editing"
msgstr "Szabványos szerkesztés"

#: ../Pyblio/GnomeUI/Editor.py:1229
msgid "mandatory"
msgstr "kötelező"

#: ../Pyblio/GnomeUI/Editor.py:1295
msgid "Enter text here"
msgstr "Ide írja a szöveget"

#: ../Pyblio/GnomeUI/Editor.py:1347
msgid "New Annotation Name"
msgstr "Új magyarázat név"

#: ../Pyblio/GnomeUI/Editor.py:1353
msgid "Name of the new annotation:"
msgstr "Az új magyarázat neve:"

#: ../Pyblio/GnomeUI/Entry.py:114
#, python-format
msgid ""
"Cannot open URL:\n"
"%s"
msgstr ""
"Nem lehet megnyitni az URL-t:\n"
"%s"

#: ../Pyblio/GnomeUI/Fields.py:38
msgid "Authors"
msgstr "Szerzők"

#: ../Pyblio/GnomeUI/Fields.py:40
msgid "Long Text"
msgstr "Hosszú szöveg"

#: ../Pyblio/GnomeUI/Fields.py:41 ../Pyblio/GnomeUI/glade/config1.glade.h:9
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:8
msgid "URL"
msgstr "URL"

#: ../Pyblio/GnomeUI/Fields.py:42
msgid "Reference"
msgstr "Hivatkozás"

#: ../Pyblio/GnomeUI/Fields.py:43
msgid "Date"
msgstr "Dátum"

#: ../Pyblio/GnomeUI/Fields.py:124 ../Pyblio/GnomeUI/glade/config1.glade.h:7
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:6
msgid "Name"
msgstr "Név"

#: ../Pyblio/GnomeUI/Fields.py:127 ../Pyblio/GnomeUI/glade/config1.glade.h:6
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:5
msgid "Type"
msgstr "Típus"

#: ../Pyblio/GnomeUI/Fields.py:300
msgid "Available"
msgstr "Elérhető"

#: ../Pyblio/GnomeUI/Fields.py:310
msgid "Associated"
msgstr "Hozzárendelt"

#: ../Pyblio/GnomeUI/Fields.py:321
msgid "Please, select an entry type from previous page."
msgstr "Válasszon egy bejegyzéstípust az előző lapról."

#: ../Pyblio/GnomeUI/Fields.py:332
#, python-format
msgid "Fields associated with <b>%s</b> entry type"
msgstr "A(z) <b>%s</b> bejegyzéstípushoz hozzárendelt mezők"

#: ../Pyblio/GnomeUI/FileSelector.py:39
msgid "File"
msgstr "Fájl"

#: ../Pyblio/GnomeUI/FileSelector.py:76
#: ../Pyblio/GnomeUI/glade/openurl.glade.h:4
msgid "Bibliography type:"
msgstr "Irodalomjegyzék típusa:"

#: ../Pyblio/GnomeUI/FileSelector.py:93 ../Pyblio/GnomeUI/OpenURL.py:61
msgid " - According to file suffix - "
msgstr " - A fájl utótagjának megfelelően - "

#. The root of the search tree is the full database
#: ../Pyblio/GnomeUI/Search.py:71
msgid "Full database"
msgstr "Teljes adatbázis"

#: ../Pyblio/GnomeUI/Search.py:142
msgid "internal error during evaluation"
msgstr "belső hiba a kiértékelés során"

#: ../Pyblio/GnomeUI/Search.py:196
#, python-format
msgid ""
"while compiling %s\n"
"error: %s"
msgstr ""
"%s fordítása során\n"
"hiba: %s"

#. These are additional search fields
#: ../Pyblio/GnomeUI/Sort.py:97
msgid "[Entry Type]"
msgstr "[Bejegyzés típusa]"

#: ../Pyblio/GnomeUI/Sort.py:98
msgid "[Key Value]"
msgstr "[Kulcs értéke]"

#: ../Pyblio/GnomeUI/Utils.py:203
msgid "The following errors occured:\n"
msgstr "A következő hibák fordultak elő:\n"

#: ../Pyblio/GnomeUI/__init__.py:45
#, python-format
msgid "This is Pybliographic %s [Python %s, Gtk %s, PyGTK %s]"
msgstr "Ez a Pybliographic %s [Python %s, Gtk %s, PyGTK %s]"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:1
msgid "Pybliographer Configuration"
msgstr "Pybliographer beállításai"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:2
msgid "FIELDS DEFINITION"
msgstr "MEZŐK DEFINÍCIÓJA"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:3
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:2
msgid "Name "
msgstr "Név "

#: ../Pyblio/GnomeUI/glade/config1.glade.h:4
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:3
msgid "Editor"
msgstr "Szerkesztő"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:5
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:4
#: ../Pyblio/GnomeUI/glade/medline.glade.h:5
#: ../Pyblio/GnomeUI/glade/openurl.glade.h:3
#: ../Pyblio/GnomeUI/glade/search.glade.h:5
msgid "*"
msgstr "*"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:8
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:7
msgid "Datum"
msgstr "Adat"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:11
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:10
msgid "Fields "
msgstr "Mezők "

#: ../Pyblio/GnomeUI/glade/config1.glade.h:13
msgid "A"
msgstr "Egy"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:14
msgid "standard fields"
msgstr "szabványos mezők"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:15
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:19
msgid "Entries"
msgstr "Bejegyzések"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:16
msgid "<b>Entry type</b>"
msgstr "<b>Bejegyzés típusa</b>"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:17
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:21
msgid "Association"
msgstr "Hozzárendelés"

#: ../Pyblio/GnomeUI/glade/fields1.glade.h:1
msgid "Entry types and field names configuration"
msgstr "Bejegyzéstípusok és mezőnevek beállítása"

#: ../Pyblio/GnomeUI/glade/fields1.glade.h:12
msgid ""
"Select an entry type and specify \n"
"its associated (mandatory and\n"
"optional) fields on the next page.\n"
"\n"
"\n"
"\n"
msgstr ""
"Válasszon egy bejegyzéstípust és \n"
"határozza meg a hozzárendelendő\n"
"(kötelező és opcionális) mezőket\n"
"a következő lapon.\n"
"\n"
"\n"

#: ../Pyblio/GnomeUI/glade/fields1.glade.h:20
msgid "Information for <b>Article</b> entry type"
msgstr "Információ az <b>Article</b> bejegyzés típushoz"

#: ../Pyblio/GnomeUI/glade/format.glade.h:1
msgid "Format entries"
msgstr "Bejegyzések formázása"

#: ../Pyblio/GnomeUI/glade/format.glade.h:2
msgid "Bibliography style:"
msgstr "Irodalomjegyzék stílusa:"

#: ../Pyblio/GnomeUI/glade/format.glade.h:3
msgid "Output format:"
msgstr "Kimeneti formátum:"

#: ../Pyblio/GnomeUI/glade/format.glade.h:4
msgid "Style Selection"
msgstr "Stílus kiválasztás"

#: ../Pyblio/GnomeUI/glade/format.glade.h:5
msgid "Save Formatted as"
msgstr "Mentés formázva másként"

#: ../Pyblio/GnomeUI/glade/format.glade.h:6
msgid "Output file:"
msgstr "Kimeneti fájl:"

#: ../Pyblio/GnomeUI/glade/medline.glade.h:1
msgid "Medline Query"
msgstr "Medline keresés"

#: ../Pyblio/GnomeUI/glade/medline.glade.h:2
msgid "Enter your Medline Query"
msgstr "Adja meg a Medline keresést"

#: ../Pyblio/GnomeUI/glade/medline.glade.h:3
msgid ""
"Search \n"
"PubMed for:"
msgstr ""
"PubMed \n"
"keresés kulcsszava:"

#: ../Pyblio/GnomeUI/glade/medline.glade.h:6
msgid ""
"Maximum number\n"
"of results:"
msgstr ""
"Találatok maximális\n"
"száma:"

#: ../Pyblio/GnomeUI/glade/medline.glade.h:8
msgid ""
"Starting listing at\n"
"result number:"
msgstr ""
"Felsorolás kezdete a\n"
"találat számával:"

#: ../Pyblio/GnomeUI/glade/medline.glade.h:10
msgid ""
"Only items \n"
"with abstracts"
msgstr ""
"Csak absztrakttal \n"
"rendelkező elemek"

#: ../Pyblio/GnomeUI/glade/medline.glade.h:12
msgid ""
"Only items \n"
"ahead of print"
msgstr ""
"Csak nyomtatás \n"
"előtt álló elemek"

#: ../Pyblio/GnomeUI/glade/medline.glade.h:14
msgid "From:"
msgstr "Ettől:"

#: ../Pyblio/GnomeUI/glade/medline.glade.h:15
msgid "To:"
msgstr "Eddig:"

#: ../Pyblio/GnomeUI/glade/medline.glade.h:16
msgid ""
"Use the format YYYY/MM/DD\n"
"Month and day are optional."
msgstr ""
"Formátum: Év/Hó/Nap (2003/11/20)\n"
"Hónap és nap megadása nem kötelező."

#: ../Pyblio/GnomeUI/glade/medline.glade.h:18
msgid "Limited to:"
msgstr "Korlátozva erre:"

#: ../Pyblio/GnomeUI/glade/openurl.glade.h:1
msgid "Open Location"
msgstr "Hely megnyitása"

#: ../Pyblio/GnomeUI/glade/openurl.glade.h:2
msgid "Enter the location (URI) of the file you would like to open:"
msgstr "Írja be a megnyitandó fájl helyét (URI):"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:1
msgid "Pybliographer"
msgstr "Pybliographer"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:2
msgid "_New"
msgstr "Ú_j"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:5
msgid "Previous Documents"
msgstr "Előző dokumentumok"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:6
msgid "_Add..."
msgstr "_Hozzáadás…"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:7
msgid "_Edit..."
msgstr "S_zerkesztés…"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:8
msgid "_Delete..."
msgstr "_Törlés…"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:10
msgid "Cite"
msgstr "Idézés"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:13
msgid "Settings"
msgstr "Beállítások"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:16
msgid "Contents"
msgstr "Tartalom"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:17
msgid "Open File"
msgstr "Fájl megnyitása"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:18
msgid "Save File"
msgstr "Fájl mentése"

#: ../Pyblio/GnomeUI/glade/search.glade.h:1
msgid "Search"
msgstr "Keresés"

#: ../Pyblio/GnomeUI/glade/search.glade.h:2
msgid "Close"
msgstr "Bezárás"

#: ../Pyblio/GnomeUI/glade/search.glade.h:3
msgid "Field"
msgstr "Mező"

#: ../Pyblio/GnomeUI/glade/search.glade.h:4
msgid "Pattern"
msgstr "Minta"

#: ../Pyblio/GnomeUI/glade/search.glade.h:6
msgid "Simple Search"
msgstr "Egyszerű keresés"

#: ../Pyblio/GnomeUI/glade/search.glade.h:7
msgid "Query"
msgstr "Lekérdezés"

#: ../Pyblio/GnomeUI/glade/search.glade.h:8
msgid "Expert Search"
msgstr "Haladó keresés"

#: ../Pyblio/GnomeUI/glade/sort.glade.h:1
msgid "Select sort criterions"
msgstr "Rendezési feltétel kiválasztása"

#: ../Pyblio/GnomeUI/glade/sort.glade.h:2
msgid "Set as default"
msgstr "Beállítás alapértelmezettként"

#: ../Pyblio/LyX.py:37
#, python-format
msgid "no input pipe `%s'"
msgstr "nincs „%s” bemeneti cső"

#: ../Pyblio/LyX.py:43
#, python-format
msgid "no output pipe `%s'"
msgstr "nincs „%s” kimeneti cső"

#: ../Pyblio/Open.py:96
#, python-format
msgid "method `%s' provides no opener"
msgstr "a(z) „%s” módszer nem biztosít megnyitót"

#: ../Pyblio/Open.py:104 ../Pyblio/Open.py:151
#, python-format
msgid "File `%s' does not exist"
msgstr "A(z) „%s” fájl nem létezik"

#: ../Pyblio/Open.py:115 ../Pyblio/Open.py:162
#, python-format
msgid "don't know how to open `%s'"
msgstr "nem tudom, hogy hogyan nyissam meg a(z) „%s” fájlt"

#: ../Pyblio/Open.py:143
#, python-format
msgid "method `%s' provides no iterator"
msgstr "a(z) „%s” módszer nem biztosít iterátort"

#: ../Pyblio/Resource.py:77
#, python-format
msgid ""
"Warning: This URL is marked as Invalid or Approximate: %s\n"
"Continue?"
msgstr ""
"Figyelmeztetés: Ez az URL érvénytelennek vagy közelítőnek van megjelölve: "
"%s\n"
"Folytatja?"

#: ../Pyblio/Resource.py:81
msgid "Determining Mime Type ... "
msgstr "MIME-típus meghatározása… "

#: ../Pyblio/Resource.py:86
#, python-format
msgid "Cannot determine mime type for item %s "
msgstr "Nem lehet meghatározni a(z) %s elem MIME-típusát "

#: ../Pyblio/Resource.py:87
#, python-format
msgid ""
"URL in question is: %s\n"
"You should check the url or path given for errors.\n"
"Details: %s"
msgstr ""
"A kérdéses URL: %s\n"
"Ellenőrizze nem hibás-e az url vagy az elérési út.\n"
"Részletek: %s"

#: ../Pyblio/Resource.py:98
msgid "Accessing resource ..."
msgstr "Hozzáférés az erőforráshoz…"

#: ../Pyblio/Resource.py:116
#, python-format
msgid "IOError for item %s: cannot uncompress resource."
msgstr "I/O hiba a(z) %s elem esetén: nem lehet kibontani az erőforrást."

#: ../Pyblio/Resource.py:117
#, python-format
msgid ""
"URL: %s\n"
"Details: %s"
msgstr ""
"URL: %s\n"
"Részletek: %s"

#: ../Pyblio/Resource.py:137
msgid "Starting application ..."
msgstr "Alkalmazás indítása…"

#: ../Pyblio/Resource.py:140
msgid "No application to view resource"
msgstr "Nincs alkalmazás az erőforrás megtekintéséhez"

#: ../Pyblio/Resource.py:141
#, python-format
msgid ""
"For mime type %s, no entry found in \n"
"configuration option resource/viewers.\n"
"Please consider adding one.\n"
"URL: %s"
msgstr ""
"A(z) %s MIME-típushoz nincs alkalmazás társítva\n"
"a Resource/Viewers beállításai között.\n"
"Kérem fontolja meg, hogy hozzáad egyet.\n"
"URL: %s"

#: ../Pyblio/Style/Parser.py:261
#, python-format
msgid "missing '%s' attribute"
msgstr "hiányzó „%s” attribútum"

#: ../Pyblio/Style/Parser.py:271
#, python-format
msgid "invalid opening tag: %s"
msgstr "érvénytelen nyitócímke: %s"

#: ../Pyblio/Style/Parser.py:281
#, python-format
msgid "invalid closing tag: %s"
msgstr "érvénytele zárócímke: %s"

#: ../pybliographer.py:43
#, python-format
msgid "This is %s, version %s"
msgstr "Ez a(z) %s, %s verzió"

#: ../pybliographer.py:47 ../pybliographer.py:54
msgid "This is free software with ABSOLUTELY NO WARRANTY."
msgstr "Ez egy szabad szoftver, amelyre SEMMIFÉLE GARANCIA nem érvényes."

#: ../pybliographer.py:48
msgid "For details, type `warranty'."
msgstr "A részletek megtekintéséhez írja be: „warranty”."

#: ../pybliographer.py:111 ../pybliographer.py:163
#, python-format
msgid "%s: error: can't open file `%s'"
msgstr "%s: hiba: nem lehet megnyitni a(z) „%s” fájlt"

#: ../pybliographer.py:124
#, python-format
msgid "For help, run %s and type `help' at the prompt"
msgstr ""
"A súgóhoz futtassa a(z) %s parancsot, és a parancssorban írja be: „help”"

#: ../pybliographer.py:133
msgid ""
"Useful commands:\n"
"\thelp     to get some help\n"
"\tquit     to quit\n"
msgstr ""
"Hasznos parancsok:\n"
"\thelp     súgóhoz\n"
"\tquit     kilépéshez\n"

#. save history
#: ../pybliographic.desktop.in.h:1
msgid "Pybliographic Bibliography Manager"
msgstr "Pybliographic irodalomjegyzék-kezelő"

#: ../pybliographic.desktop.in.h:2
msgid "Bibliography Manager"
msgstr "Irodalomjegyzék-kezelő"

#: ../pybliographic.desktop.in.h:3
msgid "Manage bibliographic databases"
msgstr "Irodalomjegyzék adatbázisok kezelése"

#: ../scripts/pybliocheck.py:31
msgid "usage: pybliocheck <file | directory>..."
msgstr "használat: pybliocheck <fájl | könyvtár>…"

#: ../scripts/pybliocheck.py:60
#, python-format
msgid "file `%s' is ok [%d entries]"
msgstr "a(z) „%s” fájl rendben [%d bejegyzés]"

#: ../scripts/pybliocompact.py:30
msgid "usage: pybliocompact <latexfile> <bibtexfiles...>"
msgstr "használat: pybliocompact <latex fájl> <bibtex fájlok…>"

#: ../scripts/pybliocompact.py:34
#, python-format
msgid "pybliocompact: error: %s\n"
msgstr "pybliocompact: hiba: %s\n"

#: ../scripts/pybliocompact.py:99
msgid "no entry"
msgstr "nincs bejegyzés"

#: ../scripts/pybliocompact.py:162 ../scripts/pybliotext.py:240
#, python-format
msgid "can't find the following entries: %s"
msgstr "a következő bejegyzések nem találhatóak: %s"

#: ../scripts/pyblioconvert.py:29
msgid "usage: pyblioconvert <source>..<target> <input> [output]"
msgstr "használat: pyblioconvert <forrás>..<cél> <bemenet> [kimenet]"

#: ../scripts/pyblioconvert.py:38
msgid "pyblioconvert: error: bad conversion format"
msgstr "pyblioconvert: hiba: rossz konverzióformátum"

#: ../scripts/pyblioformat.py:34
msgid ""
"usage: pyblioformat [options] <database...>\n"
"\n"
"    options:\n"
"      -o file, --output=file\t\tspecify an output filename\n"
"      -s style, --style=style\t\tspecify a bibliography style\n"
"      -f format, --format=format\tspecify an output format\n"
"      -H header, --header=header\tdefines a header file\n"
"      -F footer, --footer=footer\tdefines a footer file\n"
"      -l 'output', --list='output'\tlists the available output formats\n"
"      -h, --help\t\t\tshow this help message\n"
"    "
msgstr ""
"használat: pyblioformat [opciók] <adatbázis...>\n"
"\n"
"    opciók:\n"
"      -o fájl, --output=fájl\t\tkimeneti fájl nevének megadása\n"
"      -s stílus, --style=stílus\t\tbibliográfiai stílus megadása\n"
"      -f formátum, --format=formátum\ta kimenet formátumának megadása\n"
"      -H fejléc, --header=fejléc\tfejléc fájl megadása\n"
"      -F lábléc, --footer=lábléc\tlábléc fájl megadása\n"
"      -l 'output', --list='output'\tlehetséges kimeneti formátumok listája\n"
"      -h, --help\t\t\ta súgó üzenet kiíratása\n"
"    "

#: ../scripts/pyblioformat.py:48
#, python-format
msgid "pyblioformat: error: %s\n"
msgstr "pyblioformat: hiba: %s\n"

#: ../scripts/pyblioformat.py:54
#, python-format
msgid "pyblioformat: warning: %s\n"
msgstr "pyblioformat: figyelmeztetés: %s\n"

#: ../scripts/pyblioformat.py:93 ../scripts/pybliotext.py:252
#: ../scripts/pybliotext.py:278 ../scripts/pybliotext.py:321
#, python-format
msgid "can't open `%s': %s"
msgstr "nem lehet megnyitni a(z) „%s” fájlt: %s"

#: ../scripts/pyblioformat.py:100
#, python-format
msgid "unknown list `%s'"
msgstr "a(z) „%s” lista ismeretlen"

#: ../scripts/pyblioformat.py:103
#, python-format
msgid "pyblioformat: available values for `%s':"
msgstr "pyblioformat: a(z) „%s” lehetséges értékei:"

#: ../scripts/pyblioformat.py:107
#, python-format
msgid "empty value list `%s'"
msgstr "a(z) „%s” értéklista üres"

#: ../scripts/pyblioformat.py:129
msgid "too few arguments"
msgstr "túl kevés argumentum"

#: ../scripts/pyblioformat.py:136 ../scripts/pybliotext.py:117
#, python-format
msgid "unknown output format `%s'"
msgstr "a(z) „%s” kimeneti formátum ismeretlen"

#: ../scripts/pyblioformat.py:149 ../scripts/pybliotex.py:86
#: ../scripts/pybliotext.py:94
#, python-format
msgid "can't find style `%s'"
msgstr "a(z) „%s” stílus nem található"

#: ../scripts/pyblioformat.py:152
#, python-format
msgid "pyblioformat: using style `%s', format `%s'\n"
msgstr "pyblioformat: „%s” stílus, „%s” formátum használatával\n"

#: ../scripts/pyblioformat.py:167
#, python-format
msgid "can't open header `%s': %s"
msgstr "nem lehet megnyitni a(z) „%s” fejlécet: %s"

#: ../scripts/pyblioformat.py:175
#, python-format
msgid "can't open database: %s"
msgstr "nem lehet az adatbázist megnyitni: %s"

#: ../scripts/pyblioformat.py:190
#, python-format
msgid "can't open footer `%s': %s"
msgstr "nem lehet megnyitni a(z) „%s” láblécet: %s"

#: ../scripts/pybliotex.py:34
msgid "usage: pybliotex <latexfile> [bibtexfiles...]"
msgstr "használat: pybliotex <latex fájl> [bibtex fájlok…]"

#: ../scripts/pybliotex.py:38
#, python-format
msgid "pybliotex: error: %s\n"
msgstr "pybliotex: hiba: %s\n"

#. warn the user that some entries were not found
#: ../scripts/pybliotex.py:59
msgid "pybliotex: warning: the following keys were not resolved"
msgstr "pybliotex: figyelmeztetés: a következő kulcsok nem lettek feldolgozva"

#. If the LaTeX document declares no style...
#: ../scripts/pybliotex.py:64
msgid "no style defined"
msgstr "nincs stílus definiálva"

#: ../scripts/pybliotext.py:41
msgid "usage: pybliotext [-o outputfile] [-s style] <textfile> <bibfiles...>"
msgstr ""
"használat: pybliotext [-o kimeneti fájl] [-s stílus] <szövegfájl> "
"<bibliográfia fájlok…>"

#: ../scripts/pybliotext.py:45
#, python-format
msgid "pybliotext: error: %s\n"
msgstr "pybliotext: hiba: %s\n"

#: ../scripts/pybliotext.py:50
#, python-format
msgid "pybliotext: warning: %s\n"
msgstr "pybliotext: figyelmeztetés: %s\n"

#: ../scripts/pybliotext.py:124
#, python-format
msgid "File already exists: `%s'"
msgstr "A fájl már létezik: „%s”"

#: ../scripts/pybliotext.py:127
#, python-format
msgid "A file with the same name already exists: `%s'"
msgstr "Egy fájl ilyen néven már létezik: „%s”"

#: ../scripts/pybliotext.py:178
msgid "no citation found"
msgstr "hivatkozás nem található"

#: ../scripts/pybliotext.py:193
#, python-format
msgid "pybliotext: using style `%s', format `%s'\n"
msgstr "pybliotext: „%s” stílus, „%s” formátum használatával\n"

#: ../scripts/pybliotext.py:316
#, python-format
msgid "can't create `%s'"
msgstr "nem lehet létrehozni: „%s”"

#: ../scripts/pybliotext.py:342
#, python-format
msgid "can't remove `%s'"
msgstr "nem lehet eltávolítani: „%s”"

#: ../scripts/pybliotext.py:344
msgid "Done"
msgstr "Kész"

#~ msgid "_About"
#~ msgstr "_Névjegy"

#~ msgid "Failure for item %s"
#~ msgstr "Hiba a(z) %s elem esetén"

#~ msgid ""
#~ "No viewer found in Config resource/viewers\n"
#~ "URL: %s"
#~ msgstr ""
#~ "A Resource/Viewers beállításai között nincs megfelelő alkalmazás\n"
#~ "URL: %s"

#~ msgid "Add..."
#~ msgstr "Hozzáadás..."

#~ msgid "Edit..."
#~ msgstr "Módosítás..."

#~ msgid "Delete..."
#~ msgstr "Törlés..."
