# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Free Software Foundation, Inc.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: pybliographer\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2011-04-01 18:57+0300\n"
"PO-Revision-Date: 2000-08-19 16:45+00:00\n"
"Last-Translator: Valek Filippov <frob@df.ru>\n"
"Language-Team: Russian <ru@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../Pyblio/Autoload.py:78
#, python-format
msgid "warning: can't import %s: %s"
msgstr "внимание: невозможно импортировать %s: %s"

#: ../Pyblio/Config.py:52
#, python-format
msgid "value of `%s' should be of type %s"
msgstr "значение \"%s\" должно быть типа %s"

#: ../Pyblio/Config.py:212
msgid "String"
msgstr "Строка"

#: ../Pyblio/Config.py:221
msgid "Boolean"
msgstr "Логическое"

#: ../Pyblio/Config.py:240
msgid "Integer"
msgstr "Целое"

#: ../Pyblio/Config.py:242
#, python-format
msgid "Integer under %d"
msgstr "Целое до %d"

#: ../Pyblio/Config.py:244
#, python-format
msgid "Integer over %d"
msgstr "Целое больше %d"

#: ../Pyblio/Config.py:246
#, python-format
msgid "Integer between %d and %d"
msgstr "Целое между %d и %d"

#: ../Pyblio/Config.py:258
#, python-format
msgid "Element in `%s'"
msgstr "Элемент в \"%s\""

#: ../Pyblio/Config.py:278
#, python-format
msgid "Tuple (%s)"
msgstr "Кортеж (%s)"

#: ../Pyblio/Config.py:299
#, python-format
msgid "List (%s)"
msgstr "Список (%s)"

#: ../Pyblio/Config.py:324
#, python-format
msgid "Dictionary (%s, %s)"
msgstr "Словарь (%s, %s)"

#: ../Pyblio/Config.py:344
#, python-format
msgid "warning: could not restore setting %r to %r: %s"
msgstr ""

#: ../Pyblio/Fields.py:261
msgid "Illegal year value"
msgstr "Недопустимое значение года"

#: ../Pyblio/Fields.py:265
msgid "Illegal month value"
msgstr "Недопустимое значение месяца"

#: ../Pyblio/Fields.py:269
msgid "Illegal day value"
msgstr "Недопустимое значение дня"

#: ../Pyblio/Fields.py:510
#, python-format
msgid "in %s"
msgstr "в %s"

# .././Pyblio/Format/BibTeX.py:345 :403
#: ../Pyblio/Format/BibTeX.py:323 ../Pyblio/Format/BibTeX.py:371
#, python-format
msgid "key `%s' is malformed"
msgstr ""

# .././Pyblio/Format/BibTeX.py:366 :387
#: ../Pyblio/Format/BibTeX.py:340 ../Pyblio/Format/BibTeX.py:359
#, python-format
msgid "%s:%d: key `%s' already defined"
msgstr "%s:%d: ключ \"%s\" уже определен"

#: ../Pyblio/GnomeUI/Config.py:147 ../Pyblio/GnomeUI/Fields.py:417
msgid ""
"Some changes require to restart Pybliographic\n"
"to be correctly taken into account"
msgstr ""
"Некоторые изменения требуют перезапуска Pybliographer\n"
"для того, чтобы они были корректно учтены"

#: ../Pyblio/GnomeUI/Config.py:429
msgid "Add"
msgstr "Добавить"

#: ../Pyblio/GnomeUI/Config.py:432
msgid "Update"
msgstr "Обновить"

# .././Pyblio/GnomeUI/Config.py:438 :536 .././Pyblio/GnomeUI/Fields.py:95 :225
#: ../Pyblio/GnomeUI/Config.py:435 ../Pyblio/GnomeUI/Config.py:549
msgid "Remove"
msgstr "Удалить"

# .././Pyblio/GnomeUI/Config.py:533 .././Pyblio/GnomeUI/Fields.py:92 :222
#: ../Pyblio/GnomeUI/Config.py:546
msgid "Set"
msgstr "Установить"

#: ../Pyblio/GnomeUI/Config.py:561
msgid "Key:"
msgstr "Ключ:"

#: ../Pyblio/GnomeUI/Config.py:563
msgid "Value:"
msgstr "Значение:"

#. id     stock            label         accel   tooltip   callback
#: ../Pyblio/GnomeUI/Document.py:145
msgid "_File"
msgstr "Файл"

#: ../Pyblio/GnomeUI/Document.py:146 ../Pyblio/GnomeUI/Document.py:195
msgid "_Edit"
msgstr "Правка"

#: ../Pyblio/GnomeUI/Document.py:147
#, fuzzy
msgid "_View"
msgstr "Новая"

# .././Pyblio/GnomeUI/Document.py:87 :101
#: ../Pyblio/GnomeUI/Document.py:148
msgid "_Cite"
msgstr "Цитата"

#: ../Pyblio/GnomeUI/Document.py:149
#, fuzzy
msgid "_Settings"
msgstr "Установки"

#: ../Pyblio/GnomeUI/Document.py:150
msgid "_Help"
msgstr "Справка"

#: ../Pyblio/GnomeUI/Document.py:151
msgid "Recent documents"
msgstr ""

#: ../Pyblio/GnomeUI/Document.py:154
#, fuzzy
msgid "Open a file"
msgstr "Открыть файл"

#: ../Pyblio/GnomeUI/Document.py:155
#, fuzzy
msgid "Open _Location"
msgstr "Расположение"

#: ../Pyblio/GnomeUI/Document.py:156
msgid "Save the current file"
msgstr ""

#: ../Pyblio/GnomeUI/Document.py:161
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:8
#, fuzzy
msgid "Merge With..."
msgstr "Объединить с..."

#: ../Pyblio/GnomeUI/Document.py:162
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:7
msgid "Medline Query..."
msgstr ""

#: ../Pyblio/GnomeUI/Document.py:170
#, fuzzy
msgid "Add a new entry"
msgstr "Создать новую запись"

#: ../Pyblio/GnomeUI/Document.py:174
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:12
msgid "S_ort..."
msgstr "Отсортировать..."

#: ../Pyblio/GnomeUI/Document.py:175
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:2
#, fuzzy
msgid "Cite..."
msgstr "Цитата"

#: ../Pyblio/GnomeUI/Document.py:175
#, fuzzy
msgid "Cite key(s)"
msgstr "Список (%s)"

#: ../Pyblio/GnomeUI/Document.py:176
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:6
#, fuzzy
msgid "Format..."
msgstr "Формат..."

#: ../Pyblio/GnomeUI/Document.py:178
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:4
#, fuzzy
msgid "Fields..."
msgstr "Поля..."

#: ../Pyblio/GnomeUI/Document.py:180
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:5
msgid "Forget all changes"
msgstr ""

#: ../Pyblio/GnomeUI/Document.py:183
#, fuzzy
msgid "_Resource"
msgstr "Переупорядочить"

#: ../Pyblio/GnomeUI/Document.py:194
#, fuzzy
msgid "_About"
msgstr "О программе..."

#: ../Pyblio/GnomeUI/Document.py:245
msgid "Quick search"
msgstr ""

#: ../Pyblio/GnomeUI/Document.py:319
msgid "Unnamed bibliographic database"
msgstr ""

#: ../Pyblio/GnomeUI/Document.py:402
#, python-format
msgid ""
"can't open file `%s' for writing:\n"
"%s"
msgstr ""
"невозможно открыть файл \"%s\" для записи:\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:423
#, python-format
msgid ""
"Error while parsing `%s':\n"
"%s"
msgstr ""
"Ошибка при анализе \"%s\":\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:439
msgid "New database"
msgstr "Новая база данных"

# .././Pyblio/GnomeUI/Document.py:270 :274
#: ../Pyblio/GnomeUI/Document.py:447 ../Pyblio/GnomeUI/Document.py:451
msgid "[no entry]"
msgstr "[нет записей]"

#: ../Pyblio/GnomeUI/Document.py:448
msgid "[1 entry]"
msgstr "[1 запись]"

#: ../Pyblio/GnomeUI/Document.py:449
#, python-format
msgid "[%d entries]"
msgstr "[%d записей]"

#: ../Pyblio/GnomeUI/Document.py:452
#, python-format
msgid "[%d/1 entry]"
msgstr "[%d/1 записей]"

#: ../Pyblio/GnomeUI/Document.py:453
#, python-format
msgid "[%d/%d entries]"
msgstr "[%d/%d записей]"

#: ../Pyblio/GnomeUI/Document.py:458
msgid "[modified]"
msgstr "[изменено]"

#: ../Pyblio/GnomeUI/Document.py:461
#, python-format
msgid "view limited to: %s"
msgstr ""

#: ../Pyblio/GnomeUI/Document.py:474
#, fuzzy
msgid ""
"The database has been modified.\n"
"Discard changes?"
msgstr ""
"База данных была изменена.\n"
"Отменить изменения?"

#: ../Pyblio/GnomeUI/Document.py:478
#, fuzzy
msgid ""
"The database has been modified.\n"
"Save changes?"
msgstr ""
"База данных была изменена.\n"
"Отменить изменения?"

#: ../Pyblio/GnomeUI/Document.py:495
#, fuzzy
msgid ""
"The database has been externally modified.\n"
"Overwrite changes ?"
msgstr ""
"База данных была изменена.\n"
"Отменить изменения?"

#. no result.
#: ../Pyblio/GnomeUI/Document.py:524
msgid "Your query returned no result"
msgstr ""

#. get a new file name
#: ../Pyblio/GnomeUI/Document.py:534
msgid "Merge file"
msgstr "Объединить файл"

# .././Pyblio/GnomeUI/Document.py:319 :379
#: ../Pyblio/GnomeUI/Document.py:547 ../Pyblio/GnomeUI/Document.py:634
msgid "Open error"
msgstr "Ошибка открытия"

#: ../Pyblio/GnomeUI/Document.py:571
msgid "Merge status"
msgstr "Состояние объединения"

#. get a new file name
#: ../Pyblio/GnomeUI/Document.py:582
msgid "Open file"
msgstr "Открыть файл"

#: ../Pyblio/GnomeUI/Document.py:620
msgid ""
"An autosave file was found which is newer than the original file.\n"
"Do you want to restore it?"
msgstr ""

#: ../Pyblio/GnomeUI/Document.py:655 ../Pyblio/GnomeUI/Document.py:796
#: ../Pyblio/GnomeUI/Document.py:856
#, fuzzy, python-format
msgid ""
"Unable to remove autosave file `%s':\n"
"%s"
msgstr ""
"Невозможно сохранить \"%s\":\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:706
#, fuzzy, python-format
msgid ""
"Error during autosaving:\n"
"%s"
msgstr ""
"При открытии:\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:734
#, python-format
msgid ""
"Unable to save `%s':\n"
"%s"
msgstr ""
"Невозможно сохранить \"%s\":\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:742
msgid ""
"An internal error occured during saving\n"
"Try to Save As..."
msgstr ""
"При сохранении возникла внутренняя ошибка\n"
"Попробуйте \"Сохранить как...\""

#: ../Pyblio/GnomeUI/Document.py:757
msgid "Save As..."
msgstr "Сохранить как..."

#: ../Pyblio/GnomeUI/Document.py:763
#, python-format
msgid ""
"The file `%s' already exists.\n"
"Overwrite it ?"
msgstr ""
"Файл \"%s\" уже существует.\n"
"Переписать его?"

#: ../Pyblio/GnomeUI/Document.py:770
#, python-format
msgid ""
"During opening:\n"
"%s"
msgstr ""
"При открытии:\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:808
msgid "Reopen error"
msgstr "Ошибка повторного открытия"

#: ../Pyblio/GnomeUI/Document.py:881
#, python-format
msgid ""
"An entry called `%s' already exists.\n"
"Rename and add it anyway ?"
msgstr ""
"Запись с названием \"%s\" уже существует.\n"
"Переименовать и добавить в любом случае?"

#: ../Pyblio/GnomeUI/Document.py:918
msgid "Really remove all the entries ?"
msgstr "Действительно удалить все записи?"

#: ../Pyblio/GnomeUI/Document.py:938
msgid "Create new entry"
msgstr "Создать новую запись"

#: ../Pyblio/GnomeUI/Document.py:952
#, python-format
msgid "Really edit %d entries ?"
msgstr "Действительно исправить %d записей?"

#: ../Pyblio/GnomeUI/Document.py:998
#, python-format
msgid "Remove all the %d entries ?"
msgstr "Удалить все %d записей?"

#: ../Pyblio/GnomeUI/Document.py:1000
#, python-format
msgid "Remove entry `%s' ?"
msgstr "Удалить запись \"%s\"?"

#: ../Pyblio/GnomeUI/Document.py:1019
msgid ""
"your search text must contain\n"
"latin-1 characters only"
msgstr ""

# .././Pyblio/GnomeUI/Document.py:661 :668
#: ../Pyblio/GnomeUI/Document.py:1098 ../Pyblio/GnomeUI/Document.py:1106
#, python-format
msgid ""
"Can't connect to LyX:\n"
"%s"
msgstr ""
"Невозможно подключиться к LyX:\n"
"%s"

#: ../Pyblio/GnomeUI/Document.py:1221
#, python-format
msgid ""
"Can't display documentation:\n"
"%s"
msgstr ""

#: ../Pyblio/GnomeUI/Document.py:1229
msgid "This program is copyrighted under the GNU GPL"
msgstr "Эта программа защищена лицензией GNU GPL"

#: ../Pyblio/GnomeUI/Document.py:1230
#, fuzzy
msgid "GNOME interface to the Pybliographer system."
msgstr "Интерфейс Gnome к системе Pybliographer."

#: ../Pyblio/GnomeUI/Document.py:1241
msgid "GNOME Translation Team"
msgstr ""

#: ../Pyblio/GnomeUI/Document.py:1246
msgid "Pybliographer Home Page"
msgstr "Домашняя страница Pybliographer"

#: ../Pyblio/GnomeUI/Editor.py:35
msgid "Last Name, First Name"
msgstr "Фамилия, Имя"

#: ../Pyblio/GnomeUI/Editor.py:36 ../Pyblio/GnomeUI/Editor.py:1292
#: ../Pyblio/GnomeUI/Fields.py:39 ../Pyblio/GnomeUI/glade/config1.glade.h:14
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:19
msgid "Text"
msgstr "Текст"

#: ../Pyblio/GnomeUI/Editor.py:133 ../Pyblio/GnomeUI/Editor.py:1003
msgid "Error in native string parsing"
msgstr "Ошибка в анализе естественной строки"

#: ../Pyblio/GnomeUI/Editor.py:312
msgid "Day"
msgstr "День"

#: ../Pyblio/GnomeUI/Editor.py:321
msgid "Month"
msgstr "Месяц"

#: ../Pyblio/GnomeUI/Editor.py:330
msgid "Year"
msgstr "Год"

#: ../Pyblio/GnomeUI/Editor.py:355
msgid "Invalid day field in date"
msgstr "Неверное поле дня в дате"

#: ../Pyblio/GnomeUI/Editor.py:363
msgid "Invalid month field in date"
msgstr "Неверное поле месяца в дате"

#: ../Pyblio/GnomeUI/Editor.py:371
msgid "Invalid year field in date"
msgstr "Неверное поле года в дате"

#. A delete button
#: ../Pyblio/GnomeUI/Editor.py:419 ../Pyblio/GnomeUI/Search.py:86
msgid "Delete"
msgstr "Удалить"

#: ../Pyblio/GnomeUI/Editor.py:430 ../Pyblio/GnomeUI/Editor.py:443
#: ../Pyblio/GnomeUI/Editor.py:446
msgid "[ Drop an Entry here ]"
msgstr ""

#: ../Pyblio/GnomeUI/Editor.py:502
msgid "Browse..."
msgstr ""

#: ../Pyblio/GnomeUI/Editor.py:525
#, fuzzy
msgid "Select file"
msgstr "Выбрать стиль"

#: ../Pyblio/GnomeUI/Editor.py:549 ../Pyblio/GnomeUI/Fields.py:236
#: ../Pyblio/GnomeUI/glade/config1.glade.h:8
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:6
msgid "Entry type"
msgstr "Тип записи"

#: ../Pyblio/GnomeUI/Editor.py:551
msgid "Key"
msgstr "Ключ"

#: ../Pyblio/GnomeUI/Editor.py:600
msgid "Create Field"
msgstr "Создать поле"

#. navigation buttons
#: ../Pyblio/GnomeUI/Editor.py:605
msgid "Back"
msgstr ""

#: ../Pyblio/GnomeUI/Editor.py:608
#, fuzzy
msgid "Next"
msgstr "Текст"

#: ../Pyblio/GnomeUI/Editor.py:728 ../Pyblio/GnomeUI/Fields.py:451
msgid "Mandatory"
msgstr "Обязательное"

#: ../Pyblio/GnomeUI/Editor.py:728 ../Pyblio/GnomeUI/Fields.py:452
msgid "Optional"
msgstr "Необязательное"

#: ../Pyblio/GnomeUI/Editor.py:728 ../Pyblio/GnomeUI/Editor.py:1207
#, fuzzy
msgid "Notes"
msgstr "Примечание"

#: ../Pyblio/GnomeUI/Editor.py:728
msgid "Extra"
msgstr "Дополнительное"

#: ../Pyblio/GnomeUI/Editor.py:909
msgid "Invalid key format"
msgstr "Неверный формат ключа"

#: ../Pyblio/GnomeUI/Editor.py:917
#, python-format
msgid "Key `%s' already exists"
msgstr "Ключ \"%s\" уже существует"

#: ../Pyblio/GnomeUI/Editor.py:934
#, python-format
msgid "The `%s' field contains a non Latin-1 symbol"
msgstr ""

#: ../Pyblio/GnomeUI/Editor.py:996
msgid "Your text contains non Latin-1 symbols"
msgstr ""

#: ../Pyblio/GnomeUI/Editor.py:1023
msgid "Edit entry"
msgstr "Правка записи"

# .././Pyblio/GnomeUI/Editor.py:698 :739
#: ../Pyblio/GnomeUI/Editor.py:1037 ../Pyblio/GnomeUI/Editor.py:1102
msgid "Native Editing"
msgstr "Естественная правка"

#: ../Pyblio/GnomeUI/Editor.py:1125
msgid "Standard Editing"
msgstr "Стандартная правка"

#: ../Pyblio/GnomeUI/Editor.py:1229
#, fuzzy
msgid "mandatory"
msgstr "Обязательное"

#: ../Pyblio/GnomeUI/Editor.py:1295
msgid "Enter text here"
msgstr ""

#: ../Pyblio/GnomeUI/Editor.py:1347
msgid "New Annotation Name"
msgstr ""

#: ../Pyblio/GnomeUI/Editor.py:1353
msgid "Name of the new annotation:"
msgstr ""

# .././Pyblio/GnomeUI/Document.py:661 :668
#: ../Pyblio/GnomeUI/Entry.py:114
#, fuzzy, python-format
msgid ""
"Cannot open URL:\n"
"%s"
msgstr ""
"Невозможно подключиться к LyX:\n"
"%s"

#: ../Pyblio/GnomeUI/Fields.py:38
#, fuzzy
msgid "Authors"
msgstr "Автор"

#: ../Pyblio/GnomeUI/Fields.py:40
#, fuzzy
msgid "Long Text"
msgstr "Текст"

#: ../Pyblio/GnomeUI/Fields.py:41 ../Pyblio/GnomeUI/glade/config1.glade.h:16
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:21
msgid "URL"
msgstr "URL"

#: ../Pyblio/GnomeUI/Fields.py:42
msgid "Reference"
msgstr "Ссылка"

#: ../Pyblio/GnomeUI/Fields.py:43
msgid "Date"
msgstr "Дата"

#: ../Pyblio/GnomeUI/Fields.py:124 ../Pyblio/GnomeUI/glade/config1.glade.h:11
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:10
msgid "Name"
msgstr "Название"

#: ../Pyblio/GnomeUI/Fields.py:127 ../Pyblio/GnomeUI/glade/config1.glade.h:15
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:20
msgid "Type"
msgstr "Тип"

#: ../Pyblio/GnomeUI/Fields.py:300
msgid "Available"
msgstr ""

#: ../Pyblio/GnomeUI/Fields.py:310
msgid "Associated"
msgstr ""

#: ../Pyblio/GnomeUI/Fields.py:321
msgid "Please, select an entry type from previous page."
msgstr ""

#: ../Pyblio/GnomeUI/Fields.py:332
#, python-format
msgid "Fields associated with <b>%s</b> entry type"
msgstr ""

# :207
#: ../Pyblio/GnomeUI/FileSelector.py:39
msgid "File"
msgstr "Файл"

#: ../Pyblio/GnomeUI/FileSelector.py:76
#: ../Pyblio/GnomeUI/glade/openurl.glade.h:2
msgid "Bibliography type:"
msgstr "Тип библиографии:"

#: ../Pyblio/GnomeUI/FileSelector.py:93 ../Pyblio/GnomeUI/OpenURL.py:61
msgid " - According to file suffix - "
msgstr ""

#. The root of the search tree is the full database
#: ../Pyblio/GnomeUI/Search.py:71
msgid "Full database"
msgstr "Полная база данных"

#: ../Pyblio/GnomeUI/Search.py:142
msgid "internal error during evaluation"
msgstr "внутренняя ошибка при выполнении"

#: ../Pyblio/GnomeUI/Search.py:196
#, python-format
msgid ""
"while compiling %s\n"
"error: %s"
msgstr ""
"при компиляции %s\n"
"ошибка: %s"

#. These are additional search fields
#: ../Pyblio/GnomeUI/Sort.py:97
msgid "[Entry Type]"
msgstr "[Тип записи]"

#: ../Pyblio/GnomeUI/Sort.py:98
msgid "[Key Value]"
msgstr "[Значение ключа]"

#: ../Pyblio/GnomeUI/Utils.py:193
#, fuzzy
msgid "The following errors occured:\n"
msgstr ""
"Возникли следующие ошибки:\n"
"\n"

#: ../Pyblio/GnomeUI/__init__.py:45
#, python-format
msgid "This is Pybliographic %s [Python %s, Gtk %s, PyGTK %s]"
msgstr ""

#: ../Pyblio/GnomeUI/glade/config1.glade.h:1
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:1
#: ../Pyblio/GnomeUI/glade/medline.glade.h:1
#: ../Pyblio/GnomeUI/glade/openurl.glade.h:1
#: ../Pyblio/GnomeUI/glade/search.glade.h:1
msgid "*"
msgstr ""

#: ../Pyblio/GnomeUI/glade/config1.glade.h:2
#, fuzzy
msgid "<b>Entry type</b>"
msgstr "Тип записи"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:3
msgid "A"
msgstr ""

#: ../Pyblio/GnomeUI/glade/config1.glade.h:4
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:2
#, fuzzy
msgid "Association"
msgstr "Расположение"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:5
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:3
#, fuzzy
msgid "Datum"
msgstr "Дата"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:6
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:4
msgid "Editor"
msgstr "Редактор"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:7
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:5
msgid "Entries"
msgstr "Записи"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:9
msgid "FIELDS DEFINITION"
msgstr ""

#: ../Pyblio/GnomeUI/glade/config1.glade.h:10
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:8
#, fuzzy
msgid "Fields "
msgstr "Поля"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:12
#: ../Pyblio/GnomeUI/glade/fields1.glade.h:11
#, fuzzy
msgid "Name "
msgstr "Название"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:13
#, fuzzy
msgid "Pybliographer Configuration"
msgstr "Домашняя страница Pybliographer"

#: ../Pyblio/GnomeUI/glade/config1.glade.h:17
#, fuzzy
msgid "standard fields"
msgstr "Существующие поля"

#: ../Pyblio/GnomeUI/glade/fields1.glade.h:7
#, fuzzy
msgid "Entry types and field names configuration"
msgstr "Конфигурация записей"

#: ../Pyblio/GnomeUI/glade/fields1.glade.h:9
msgid "Information for <b>Article</b> entry type"
msgstr ""

#: ../Pyblio/GnomeUI/glade/fields1.glade.h:12
msgid ""
"Select an entry type and specify \n"
"its associated (mandatory and\n"
"optional) fields on the next page.\n"
"\n"
"\n"
"\n"
msgstr ""

#: ../Pyblio/GnomeUI/glade/format.glade.h:1
msgid "Bibliography style:"
msgstr "Стиль библиографии:"

#: ../Pyblio/GnomeUI/glade/format.glade.h:2
msgid "Format entries"
msgstr "Формат записей"

#: ../Pyblio/GnomeUI/glade/format.glade.h:3
#, fuzzy
msgid "Output file:"
msgstr "Файл вывода:"

#: ../Pyblio/GnomeUI/glade/format.glade.h:4
msgid "Output format:"
msgstr "Формат вывода:"

#: ../Pyblio/GnomeUI/glade/format.glade.h:5
msgid "Save Formatted as"
msgstr ""

#: ../Pyblio/GnomeUI/glade/format.glade.h:6
#, fuzzy
msgid "Style Selection"
msgstr "Направление сортировки"

#: ../Pyblio/GnomeUI/glade/medline.glade.h:2
msgid "Enter your Medline Query"
msgstr ""

#: ../Pyblio/GnomeUI/glade/medline.glade.h:3
#, fuzzy
msgid "From:"
msgstr "Из"

#: ../Pyblio/GnomeUI/glade/medline.glade.h:4
msgid "Limited to:"
msgstr ""

#: ../Pyblio/GnomeUI/glade/medline.glade.h:5
msgid ""
"Maximum number\n"
"of results:"
msgstr ""

#: ../Pyblio/GnomeUI/glade/medline.glade.h:7
msgid "Medline Query"
msgstr ""

#: ../Pyblio/GnomeUI/glade/medline.glade.h:8
msgid ""
"Only items \n"
"ahead of print"
msgstr ""

#: ../Pyblio/GnomeUI/glade/medline.glade.h:10
msgid ""
"Only items \n"
"with abstracts"
msgstr ""

#: ../Pyblio/GnomeUI/glade/medline.glade.h:12
msgid ""
"Search \n"
"PubMed for:"
msgstr ""

#: ../Pyblio/GnomeUI/glade/medline.glade.h:14
msgid ""
"Starting listing at\n"
"result number:"
msgstr ""

#: ../Pyblio/GnomeUI/glade/medline.glade.h:16
msgid "To:"
msgstr ""

#: ../Pyblio/GnomeUI/glade/medline.glade.h:17
msgid ""
"Use the format YYYY/MM/DD\n"
"Month and day are optional."
msgstr ""

#: ../Pyblio/GnomeUI/glade/openurl.glade.h:3
msgid "Enter the location (URI) of the file you would like to open:"
msgstr ""

#: ../Pyblio/GnomeUI/glade/openurl.glade.h:4
#, fuzzy
msgid "Open Location"
msgstr "Расположение"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:1
msgid "Cite"
msgstr "Цитата"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:3
#, fuzzy
msgid "Contents"
msgstr "Cote"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:9
#, fuzzy
msgid "Open File"
msgstr "Открыть файл"

# .././Pyblio/GnomeUI/Document.py:193 :207
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:10
msgid "Previous Documents"
msgstr "Предыдущие документы"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:11
#, fuzzy
msgid "Pybliographer"
msgstr "Домашняя страница Pybliographer"

# :207
#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:13
#, fuzzy
msgid "Save File"
msgstr "Файл"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:14
#, fuzzy
msgid "Settings"
msgstr "Установки"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:15
msgid "_Add..."
msgstr "Добавить..."

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:16
#, fuzzy
msgid "_Delete..."
msgstr "Удалить"

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:17
msgid "_Edit..."
msgstr "Правка..."

#: ../Pyblio/GnomeUI/glade/pyblio.glade.in.h:18
msgid "_New"
msgstr "Новая"

#: ../Pyblio/GnomeUI/glade/search.glade.h:2
msgid "Close"
msgstr "Закрыть"

#: ../Pyblio/GnomeUI/glade/search.glade.h:3
msgid "Expert Search"
msgstr "Экспертный поиск"

#: ../Pyblio/GnomeUI/glade/search.glade.h:4
msgid "Field"
msgstr "Поле"

#: ../Pyblio/GnomeUI/glade/search.glade.h:5
msgid "Pattern"
msgstr "Шаблон"

#: ../Pyblio/GnomeUI/glade/search.glade.h:6
msgid "Query"
msgstr ""

#: ../Pyblio/GnomeUI/glade/search.glade.h:7
msgid "Search"
msgstr "Поиск"

#: ../Pyblio/GnomeUI/glade/search.glade.h:8
msgid "Simple Search"
msgstr "Простой поиск"

#: ../Pyblio/GnomeUI/glade/sort.glade.h:1
msgid "Select sort criterions"
msgstr "Выберите критерии сортировки"

#: ../Pyblio/GnomeUI/glade/sort.glade.h:2
msgid "Set as default"
msgstr ""

#: ../Pyblio/LyX.py:37
#, python-format
msgid "no input pipe `%s'"
msgstr "нет канала ввода \"%s\""

#: ../Pyblio/LyX.py:43
#, python-format
msgid "no output pipe `%s'"
msgstr "нет канала вывода \"%s\""

#: ../Pyblio/Open.py:96
#, python-format
msgid "method `%s' provides no opener"
msgstr ""

# .././Pyblio/Open.py:105 :151
#: ../Pyblio/Open.py:104 ../Pyblio/Open.py:151
#, python-format
msgid "File `%s' does not exist"
msgstr "Файл \"%s\" не существует"

# .././Pyblio/Open.py:116 :162
#: ../Pyblio/Open.py:115 ../Pyblio/Open.py:162
#, python-format
msgid "don't know how to open `%s'"
msgstr "не известно как открыть \"%s\""

#: ../Pyblio/Open.py:143
#, python-format
msgid "method `%s' provides no iterator"
msgstr ""

#: ../Pyblio/Resource.py:77
#, python-format
msgid ""
"Warning: This URL is marked as Invalid or Approximate: %s\n"
"Continue?"
msgstr ""

#: ../Pyblio/Resource.py:81
msgid "Determining Mime Type ... "
msgstr ""

#: ../Pyblio/Resource.py:86
#, python-format
msgid "Cannot determine mime type for item %s "
msgstr ""

#: ../Pyblio/Resource.py:87
#, python-format
msgid ""
"URL in question is: %s\n"
"You should check the url or path given for errors.\n"
"Details: %s"
msgstr ""

#: ../Pyblio/Resource.py:98
msgid "Accessing resource ..."
msgstr ""

#: ../Pyblio/Resource.py:116
#, python-format
msgid "IOError for item %s: cannot uncompress resource."
msgstr ""

#: ../Pyblio/Resource.py:117
#, python-format
msgid ""
"URL: %s\n"
"Details: %s"
msgstr ""

#: ../Pyblio/Resource.py:137
msgid "Starting application ..."
msgstr ""

#: ../Pyblio/Resource.py:140
msgid "No application to view resource"
msgstr ""

#: ../Pyblio/Resource.py:141
#, python-format
msgid ""
"For mime type %s, no entry found in \n"
"configuration option resource/viewers.\n"
"Please consider adding one.\n"
"URL: %s"
msgstr ""

#: ../Pyblio/Style/Parser.py:261
#, python-format
msgid "missing '%s' attribute"
msgstr ""

#: ../Pyblio/Style/Parser.py:271
#, fuzzy, python-format
msgid "invalid opening tag: %s"
msgstr ""
"При открытии:\n"
"%s"

#: ../Pyblio/Style/Parser.py:281
#, python-format
msgid "invalid closing tag: %s"
msgstr ""

#: ../pybliographer.py:43
#, python-format
msgid "This is %s, version %s"
msgstr "Это %s, версия %s"

# .././pybliographer.py:42 :49
#: ../pybliographer.py:47 ../pybliographer.py:54
msgid "This is free software with ABSOLUTELY NO WARRANTY."
msgstr "Это свободное программное обеспечение БЕЗ КАКИХ-ЛИБО ГАРАНТИЙ."

#: ../pybliographer.py:48
msgid "For details, type `warranty'."
msgstr "Для подробностей, наберите \"warranty\"."

# .././pybliographer.py:110 :158
#: ../pybliographer.py:111 ../pybliographer.py:163
#, python-format
msgid "%s: error: can't open file `%s'"
msgstr "%s: ошибка: невозможно открыть файл \"%s\""

#: ../pybliographer.py:124
#, python-format
msgid "For help, run %s and type `help' at the prompt"
msgstr "Для справки, запустите %s и наберите \"help\" в строке ввода"

#: ../pybliographer.py:133
msgid ""
"Useful commands:\n"
"\thelp     to get some help\n"
"\tquit     to quit\n"
msgstr ""
"Полезные команды:\n"
"        help выдает справку\n"
"        quit выход\n"

#. save history
#: ../pybliographic.desktop.in.h:1
#, fuzzy
msgid "Bibliography Manager"
msgstr "Тип библиографии:"

#: ../pybliographic.desktop.in.h:2
msgid "Manage bibliographic databases"
msgstr ""

#: ../pybliographic.desktop.in.h:3
msgid "Pybliographic Bibliography Manager"
msgstr ""

#: ../scripts/pybcheck.py:31
msgid "usage: pybcheck <file | directory>..."
msgstr ""

# .././Pyblio/Open.py:105 :151
#: ../scripts/pybcheck.py:60
#, fuzzy, python-format
msgid "file `%s' is ok [%d entries]"
msgstr "Файл \"%s\" не существует"

#: ../scripts/pybcompact.py:30
msgid "usage: pybcompact <latexfile> <bibtexfiles...>"
msgstr "использование: pybcompact <latexfile> <bibtexfiles...>"

#: ../scripts/pybcompact.py:34
#, python-format
msgid "pybcompact: error: %s\n"
msgstr "pybcompact: ошибка: %s\n"

#: ../scripts/pybcompact.py:99
msgid "no entry"
msgstr "нет записей"

#: ../scripts/pybcompact.py:162 ../scripts/pybtext.py:240
#, python-format
msgid "can't find the following entries: %s"
msgstr "не удалось найти следующие записи: %s"

#: ../scripts/pybconvert.py:29
msgid "usage: pybconvert <source>..<target> <input> [output]"
msgstr "использование: pybconvert <source>..<target> <input> [output]"

#: ../scripts/pybconvert.py:38
#, fuzzy
msgid "pybconvert: error: bad conversion format"
msgstr "pybconvert: плохой формат преобразования"

#: ../scripts/pybformat.py:34
msgid ""
"usage: pybformat [options] <database...>\n"
"\n"
"    options:\n"
"      -o file, --output=file\t\tspecify an output filename\n"
"      -s style, --style=style\t\tspecify a bibliography style\n"
"      -f format, --format=format\tspecify an output format\n"
"      -H header, --header=header\tdefines a header file\n"
"      -F footer, --footer=footer\tdefines a footer file\n"
"      -l 'output', --list='output'\tlists the available output formats\n"
"      -h, --help\t\t\tshow this help message\n"
"    "
msgstr ""

#: ../scripts/pybformat.py:48
#, python-format
msgid "pybformat: error: %s\n"
msgstr "pybformat: ошибка %s\n"

#: ../scripts/pybformat.py:54
#, python-format
msgid "pybformat: warning: %s\n"
msgstr "pybformat: внимание: %s\n"

#: ../scripts/pybformat.py:93 ../scripts/pybtext.py:252
#: ../scripts/pybtext.py:278 ../scripts/pybtext.py:321
#, fuzzy, python-format
msgid "can't open `%s': %s"
msgstr ""
"невозможно открыть файл \"%s\" для записи:\n"
"%s"

#: ../scripts/pybformat.py:100
#, python-format
msgid "unknown list `%s'"
msgstr ""

#: ../scripts/pybformat.py:103
#, python-format
msgid "pybformat: available values for `%s':"
msgstr ""

#: ../scripts/pybformat.py:107
#, python-format
msgid "empty value list `%s'"
msgstr ""

#: ../scripts/pybformat.py:129
msgid "too few arguments"
msgstr ""

#: ../scripts/pybformat.py:136 ../scripts/pybtext.py:117
#, fuzzy, python-format
msgid "unknown output format `%s'"
msgstr "нет канала вывода \"%s\""

#: ../scripts/pybformat.py:149 ../scripts/pybtex.py:86
#: ../scripts/pybtext.py:94
#, python-format
msgid "can't find style `%s'"
msgstr "не удалось найти стиль \"%s\""

#: ../scripts/pybformat.py:152
#, python-format
msgid "pybformat: using style `%s', format `%s'\n"
msgstr ""

#: ../scripts/pybformat.py:167
#, fuzzy, python-format
msgid "can't open header `%s': %s"
msgstr ""
"невозможно открыть файл \"%s\" для записи:\n"
"%s"

#: ../scripts/pybformat.py:175
#, python-format
msgid "can't open database: %s"
msgstr ""

#: ../scripts/pybformat.py:190
#, fuzzy, python-format
msgid "can't open footer `%s': %s"
msgstr ""
"невозможно открыть файл \"%s\" для записи:\n"
"%s"

#: ../scripts/pybtex.py:34
msgid "usage: pybtex <latexfile> [bibtexfiles...]"
msgstr "использование: pybtex <latexfile> [bibtexfiles...]"

#: ../scripts/pybtex.py:38
#, python-format
msgid "pybtex: error: %s\n"
msgstr "pybtex: ошибка: %s\n"

#. warn the user that some entries were not found
#: ../scripts/pybtex.py:59
msgid "pybtex: warning: the following keys were not resolved"
msgstr "pybtex: внимание: следующие ключи не были распознаны"

#. If the LaTeX document declares no style...
#: ../scripts/pybtex.py:64
msgid "no style defined"
msgstr "стиль не определен"

#: ../scripts/pybtext.py:41
#, fuzzy
msgid "usage: pybtext [-o outputfile] [-s style] <textfile> <bibfiles...>"
msgstr "использование: pybcompact <latexfile> <bibtexfiles...>"

#: ../scripts/pybtext.py:45
#, fuzzy, python-format
msgid "pybtext: error: %s\n"
msgstr "pybtex: ошибка: %s\n"

#: ../scripts/pybtext.py:50
#, fuzzy, python-format
msgid "pybtext: warning: %s\n"
msgstr "pybformat: внимание: %s\n"

#: ../scripts/pybtext.py:124
#, fuzzy, python-format
msgid "File already exists: `%s'"
msgstr "Ключ \"%s\" уже существует"

#: ../scripts/pybtext.py:127
#, python-format
msgid "A file with the same name already exists: `%s'"
msgstr ""

#: ../scripts/pybtext.py:178
msgid "no citation found"
msgstr ""

#: ../scripts/pybtext.py:193
#, python-format
msgid "pybtext: using style `%s', format `%s'\n"
msgstr ""

#: ../scripts/pybtext.py:316
#, fuzzy, python-format
msgid "can't create `%s'"
msgstr "не удалось найти стиль \"%s\""

#: ../scripts/pybtext.py:342
#, fuzzy, python-format
msgid "can't remove `%s'"
msgstr "не удалось найти стиль \"%s\""

#: ../scripts/pybtext.py:344
msgid "Done"
msgstr ""
